package lr2;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gyrocopter_UA
 */
public class MyForm extends javax.swing.JFrame {
    private byte byteVar = 10;
    private short shortVar = 100;
    private int intVar = 1000;
    private long longVar = 100000L;
    private char charVar = 'A';
    private float floatVar = 3.14f;
    private double doubleVar = 2.71828;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MyForm.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public MyForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbGreet = new javax.swing.JButton();
        jbClear = new javax.swing.JButton();
        tfGreetMessage = new javax.swing.JTextField();
        jPressMe = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        jByte = new javax.swing.JButton();
        jShort = new javax.swing.JButton();
        jInt = new javax.swing.JButton();
        jLong = new javax.swing.JButton();
        jChar = new javax.swing.JButton();
        jFloat = new javax.swing.JButton();
        jDouble = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbGreet.setText("Greeting");
        jbGreet.setToolTipText("Привітання");
        jbGreet.addActionListener(this::jbGreetActionPerformed);

        jbClear.setText("Clear");
        jbClear.setToolTipText("Стерти текст");
        jbClear.addActionListener(this::jbClearActionPerformed);

        jPressMe.setText("Press me");
        jPressMe.setToolTipText("Натични мене");
        jPressMe.addActionListener(this::jPressMeActionPerformed);

        jExit.setText("Exit");
        jExit.setToolTipText("Вихід");
        jExit.addActionListener(this::jExitActionPerformed);

        jByte.setText("Byte");
        jByte.addActionListener(this::jByteActionPerformed);

        jShort.setText("Short");
        jShort.addActionListener(this::jShortActionPerformed);

        jInt.setText("Int");
        jInt.addActionListener(this::jIntActionPerformed);

        jLong.setText("Long");
        jLong.addActionListener(this::jLongActionPerformed);

        jChar.setText("Char");
        jChar.addActionListener(this::jCharActionPerformed);

        jFloat.setText("Float");
        jFloat.addActionListener(this::jFloatActionPerformed);

        jDouble.setText("Double");
        jDouble.addActionListener(this::jDoubleActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jbGreet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPressMe))
                    .addComponent(tfGreetMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jExit)
                .addGap(124, 124, 124))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jByte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jShort)
                .addGap(18, 18, 18)
                .addComponent(jInt)
                .addGap(18, 18, 18)
                .addComponent(jLong)
                .addGap(30, 30, 30)
                .addComponent(jChar)
                .addGap(18, 18, 18)
                .addComponent(jFloat)
                .addGap(28, 28, 28)
                .addComponent(jDouble)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(tfGreetMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGreet)
                    .addComponent(jbClear)
                    .addComponent(jPressMe)
                    .addComponent(jExit))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jByte)
                    .addComponent(jShort)
                    .addComponent(jInt)
                    .addComponent(jLong)
                    .addComponent(jChar)
                    .addComponent(jFloat)
                    .addComponent(jDouble))
                .addGap(126, 126, 126))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGreetActionPerformed
        tfGreetMessage.setText("Hello");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGreetActionPerformed

    private void jbClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClearActionPerformed
        tfGreetMessage.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jbClearActionPerformed

    private void jPressMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPressMeActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Мене натиснули");
        // TODO add your handling code here:
    }//GEN-LAST:event_jPressMeActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jExitActionPerformed

    private void jByteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jByteActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Назва: byteVar, Значення: " + byteVar);
        // TODO add your handling code here:
    }//GEN-LAST:event_jByteActionPerformed

    private void jShortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShortActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Назва: shortVar, Значення: " + shortVar);
        // TODO add your handling code here:
    }//GEN-LAST:event_jShortActionPerformed

    private void jIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIntActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Назва: intVar, Значення: " + intVar);
        // TODO add your handling code here:
    }//GEN-LAST:event_jIntActionPerformed

    private void jLongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLongActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Назва: longVar, Значення: " + longVar);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLongActionPerformed

    private void jCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCharActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Назва: charVar, Значення: " + charVar);
        // TODO add your handling code here:
    }//GEN-LAST:event_jCharActionPerformed

    private void jFloatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFloatActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Назва: floatVar, Значення: " + floatVar);
        // TODO add your handling code here:
    }//GEN-LAST:event_jFloatActionPerformed

    private void jDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoubleActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Назва: doubleVar, Значення: " + doubleVar);
        // TODO add your handling code here:
    }//GEN-LAST:event_jDoubleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MyForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jByte;
    private javax.swing.JButton jChar;
    private javax.swing.JButton jDouble;
    private javax.swing.JButton jExit;
    private javax.swing.JButton jFloat;
    private javax.swing.JButton jInt;
    private javax.swing.JButton jLong;
    private javax.swing.JButton jPressMe;
    private javax.swing.JButton jShort;
    private javax.swing.JButton jbClear;
    private javax.swing.JButton jbGreet;
    private javax.swing.JTextField tfGreetMessage;
    // End of variables declaration//GEN-END:variables
}
